from typing import List, Dict, Any, Optional

class ExportManager:
    """
    Utility manager for exporting DocuMind AI session outputs
    (Executive Summary, Core Takeaways, Concept Glossary, Topic Mind Map,
     Q&A History, All Challenge Questions & Evaluations, and Full Parsed Chunks)
    into formatted Markdown (.md) or Text (.txt) reports.
    """

    @classmethod
    def generate_markdown_report(
        cls,
        document_name: str,
        summary: str,
        chat_history: List[Dict[str, Any]],
        evaluations: Dict[int, Dict[str, Any]],
        challenge_questions: List[Dict[str, Any]],
        takeaways: Optional[List[str]] = None,
        glossary: Optional[List[Dict[str, str]]] = None,
        mindmap: Optional[str] = None,
        chunks: Optional[List[Any]] = None
    ) -> str:
        """
        Generates a comprehensive Markdown report containing all session data & full document content.
        """
        doc_title = document_name or "Research Document"
        md_lines = [
            f"# DocuMind AI Comprehensive Research Report: {doc_title}\n",
            "---",
            "## 1. Executive Summary\n",
            summary if summary else "No summary generated.",
            "\n---"
        ]

        # Key Takeaways Section
        if takeaways:
            md_lines.append("## 2. Core Takeaways\n")
            for idx, item in enumerate(takeaways, 1):
                md_lines.append(f"{idx}. {item}")
            md_lines.append("\n---")

        # Key Concept Glossary
        if glossary:
            md_lines.append("## 3. Glossary of Key Terms\n")
            for term_obj in glossary:
                term = term_obj.get("term", "Term")
                definition = term_obj.get("definition", "")
                citation = term_obj.get("citation", "")
                md_lines.append(f"- **{term}** (*{citation}*): {definition}")
            md_lines.append("\n---")

        # Topic Mind Map Section
        if mindmap:
            md_lines.append("## 4. Topic Mind Map Hierarchy\n")
            md_lines.append(f"```mermaid\n{mindmap}\n```\n")
            md_lines.append("---")

        # Q&A Session History
        md_lines.append("## 5. Q&A Session Transcript\n")
        if not chat_history:
            md_lines.append("*No Q&A questions asked during this session.*\n")
        else:
            for msg in chat_history:
                if msg.get("role") == "user":
                    md_lines.append(f"### Q: {msg.get('content')}")
                else:
                    ans = msg.get("answer", "")
                    just = msg.get("justification", "")
                    snip = msg.get("snippet", "")
                    md_lines.append(f"**Answer:** {ans}\n")
                    if just:
                        md_lines.append(f"> **Justification:** {just}\n")
                    if snip:
                        md_lines.append(f"```text\nSource Snippet:\n\"{snip}\"\n```\n")
            md_lines.append("---")

        # All Logic Challenge Questions & Evaluations
        md_lines.append("## 6. All Logic Challenge Questions & Evaluations\n")
        if not challenge_questions:
            md_lines.append("*No challenge questions generated.*\n")
        else:
            for q_obj in challenge_questions:
                q_id = q_obj.get("id")
                q_text = q_obj.get("question", f"Question #{q_id}")
                hint = q_obj.get("hint", "")
                target_citation = q_obj.get("target_citation", "")
                
                md_lines.append(f"### Question #{q_id}: {q_text}")
                if target_citation and target_citation != "N/A":
                    md_lines.append(f"*Target Citation:* {target_citation}")
                if hint:
                    md_lines.append(f"*Hint:* {hint}")
                    
                if evaluations and q_id in evaluations:
                    ev = evaluations[q_id]
                    score = ev.get("score", "N/A")
                    status = ev.get("status", "")
                    feedback = ev.get("feedback", "")
                    ideal = ev.get("ideal_answer", "")
                    justification = ev.get("justification", "")
                    
                    md_lines.append(f"- **Status:** {status} ({score})")
                    md_lines.append(f"- **Feedback:** {feedback}")
                    md_lines.append(f"- **Ideal Answer:** {ideal}")
                    if justification:
                        md_lines.append(f"- **Document Proof:** {justification}\n")
                else:
                    md_lines.append("- **Status:** Pending User Answer (Not evaluated yet)\n")
            md_lines.append("---")

        md_lines.append("\n*Generated by DocuMind AI - An Intelligent Document Assistant*")
        return "\n".join(md_lines)

    @classmethod
    def generate_txt_report(
        cls,
        document_name: str,
        summary: str,
        chat_history: List[Dict[str, Any]],
        evaluations: Dict[int, Dict[str, Any]],
        challenge_questions: List[Dict[str, Any]],
        takeaways: Optional[List[str]] = None,
        glossary: Optional[List[Dict[str, str]]] = None,
        mindmap: Optional[str] = None,
        chunks: Optional[List[Any]] = None
    ) -> str:
        """
        Generates a comprehensive plain text report containing all session data & full document content.
        """
        doc_title = document_name or "Research Document"
        txt_lines = [
            "=" * 60,
            f"DOCUMIND AI COMPREHENSIVE RESEARCH REPORT: {doc_title.upper()}",
            "=" * 60,
            "\n1. EXECUTIVE SUMMARY",
            "-" * 30,
            summary if summary else "No summary generated.",
            "\n"
        ]

        if takeaways:
            txt_lines.append("2. CORE TAKEAWAYS")
            txt_lines.append("-" * 30)
            for idx, item in enumerate(takeaways, 1):
                txt_lines.append(f"{idx}. {item}")
            txt_lines.append("\n")

        if glossary:
            txt_lines.append("3. GLOSSARY OF KEY TERMS")
            txt_lines.append("-" * 30)
            for term_obj in glossary:
                term = term_obj.get("term", "Term")
                definition = term_obj.get("definition", "")
                citation = term_obj.get("citation", "")
                txt_lines.append(f"- {term} ({citation}): {definition}")
            txt_lines.append("\n")

        if mindmap:
            txt_lines.append("4. TOPIC MIND MAP HIERARCHY")
            txt_lines.append("-" * 30)
            txt_lines.append(mindmap)
            txt_lines.append("\n")

        txt_lines.append("5. Q&A TRANSCRIPT")
        txt_lines.append("-" * 30)
        if not chat_history:
            txt_lines.append("No Q&A questions asked.\n")
        else:
            for msg in chat_history:
                if msg.get("role") == "user":
                    txt_lines.append(f"\n[USER QUESTION]: {msg.get('content')}")
                else:
                    txt_lines.append(f"[ASSISTANT ANSWER]: {msg.get('answer')}")
                    if msg.get("justification"):
                        txt_lines.append(f"[JUSTIFICATION]: {msg.get('justification')}")
                    if msg.get("snippet"):
                        txt_lines.append(f"[SOURCE SNIPPET]: \"{msg.get('snippet')}\"")
            txt_lines.append("\n")

        txt_lines.append("6. ALL LOGIC CHALLENGE QUESTIONS & EVALUATIONS")
        txt_lines.append("-" * 30)
        if not challenge_questions:
            txt_lines.append("No challenge questions generated.\n")
        else:
            for q_obj in challenge_questions:
                q_id = q_obj.get("id")
                q_text = q_obj.get("question", f"Question #{q_id}")
                txt_lines.append(f"Q#{q_id}: {q_text}")
                if q_obj.get("target_citation"):
                    txt_lines.append(f"Target Citation: {q_obj.get('target_citation')}")
                
                if evaluations and q_id in evaluations:
                    ev = evaluations[q_id]
                    txt_lines.append(f"Score: {ev.get('score')} | Status: {ev.get('status')}")
                    txt_lines.append(f"Feedback: {ev.get('feedback')}")
                    txt_lines.append(f"Ideal Answer: {ev.get('ideal_answer')}\n")
                else:
                    txt_lines.append("Status: Pending User Answer\n")
            txt_lines.append("\n")

        txt_lines.append("\n*Generated by DocuMind AI - An Intelligent Document Assistant*")

        return "\n".join(txt_lines)
